dbt_crash_course:
  outputs:
    dev:
      dataset: dbt-crash-course
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: ./sa/dbt-crash-course.json
      location: US
      method: service-account
      priority: interactive
      project: dbt-crash-course-430616
      threads: 1
      type: bigquery
  target: dev
